openapi: 3.0.3
info:
  title: JS Portal - JSKG API
  version: 1.0.11
tags:
  - name: Graph APIs
    description: To be done by Pillar 1 in the interim and subsequently handed over to vendors. The `/courses` API is currently blocked by the TGS dataset due to missing/dead MySF links.
  - name: Data APIs
    description: To supply information about demand for specific job roles by sector/company.
    
paths:
  /listOfJobs:
    get:
      tags:
        - Graph APIs
      summary: Get list of jobs that have valid pathways
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
              example:
                - ssocTitle: Company Director
                  ssocCode: '11202'
                - ssocTitle: Risk Management Manager
                  ssocCode: '12133'
                - ssocTitle: Financial Services Manager
                  ssocCode: '13461'
        '404':
          description: List of jobs not found
          
  /pathways/{ssocCode}:
    get:
      tags:
        - Graph APIs
      parameters:
      - name: ssocCode
        example: '25122'
        in: path
        description: Name of the job to analyse
        required: true
        schema:
          type: string
      summary: Retrieve info about pathways from a single job
      description: Provides a job name from `/listOfJobs` to get the top 10 roles from/to that job, and the skills similarity, skills gap, median wage, and job count for each entry. 
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                minItems: 10
                maxItems: 10
                items: 
                  $ref: '#/components/schemas/Pathway'
              example:
                - destinationRole: 
                    ssocTitle: 'Software Engineer'
                    ssocCode: '12323'
                  ssocSimilarityScore: 0.85
                  ssocSimilarityCategory: 'High'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 7500
                  jobCount: 500
                - destinationRole: 
                    ssocTitle: 'Marketing Manager'
                    ssocCode: '14333'
                  ssocSimilarityScore: 0.55
                  ssocSimilarityCategory: 'Medium'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 5800
                  jobCount: 250
                - destinationRole: 
                    ssocTitle: 'Financial Analyst'
                    ssocCode: '15423'
                  ssocSimilarityScore: 0.20
                  ssocSimilarityCategory: 'Low'
                  ssocSkillGap: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']
                  ssocMedianWage: 6700
                  jobCount: 120
                - destinationRole: 
                    ssocTitle: 'Operations Manager'
                    ssocCode: '12363'
                  ssocSimilarityScore: 0.80                
                  ssocSimilarityCategory: 'High'
                  ssocSkillGap: ['Skill 1']
                  ssocMedianWage: 6200
                  jobCount: 300
                - destinationRole: 
                    ssocTitle: 'Cybersecurity Specialist'
                    ssocCode: '12723'
                  ssocSimilarityScore: 0.60                
                  ssocSimilarityCategory: 'Medium'
                  ssocSkillGap: ['Skill 1']
                  ssocMedianWage: 8000
                  jobCount: 180
                - destinationRole: 
                    ssocTitle: 'Data Scientist'
                    ssocCode: '19323'      
                  ssocSimilarityScore: 0.75         
                  ssocSimilarityCategory: 'High'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 9500
                  jobCount: 400
                - destinationRole: 
                    ssocTitle: 'Human Resources Manager'
                    ssocCode: '12123' 
                  ssocSimilarityScore: 0.45              
                  ssocSimilarityCategory: 'Medium'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 6000
                  jobCount: 220
                - destinationRole: 
                    ssocTitle: 'Retail Store Manager'
                    ssocCode: '12303'
                  ssocSimilarityScore: 0.30              
                  ssocSimilarityCategory: 'Low'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 4500
                  jobCount: 150
                - destinationRole: 
                    ssocTitle: 'Mechanical Engineer'
                    ssocCode: '17323'  
                  ssocSimilarityScore: 0.60            
                  ssocSimilarityCategory: 'Medium'
                  ssocSkillGap: ['Skill 1', 'Skill 2']
                  ssocMedianWage: 7200
                  jobCount: 280
                - destinationRole: 
                    ssocTitle: 'Project Manager'
                    ssocCode: '13873'     
                  ssocSimilarityScore: 0.70        
                  ssocSimilarityCategory: 'High'
                  ssocSkillGap: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']
                  ssocMedianWage: 7000
                  jobCount: 350
        '404':
          description: Job not found
          
  /sectors/jobCount/{ssocCode}/{quarter}:
    get:
      tags:
        - Data APIs
      parameters:
      - name: ssocCode
        example: '25122'
        in: path
        description: ssoc of the job to analyse, cannot be null
        required: true
        schema:
          type: string
      - name: quarter
        example: 2025Q1
        in: path
        description: Time period for the data
        required: true
        schema:
          type: string
      - name: resultCount
        example: 20
        in: query
        description: Max number of results, if not provided to return 50
        schema:
          type: number
      - name: jobCountThreshold
        example: 20
        in: query
        description: Minimum jobCount that the results should have e.g. if set to 20, companies with 19 or less jobCount will be omitted from the response. Defaults to 1
        schema:
          type: number    
      summary: Get the demand for this job role
      description: Sort by job count descending (highest first). Data refresh cycle at 28 days after end of each quarter.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/SectorResponse'
              example:
                ssocVersion: '2020'
                ssocTitle: 'Web And Mobile Applications Developer'
                data:
                - sfwSectorTitle: 'Financial Services'
                  jobCount: 999
                - sfwSectorTitle: 'Accountancy'
                  jobCount: 998
                - sfwSectorTitle: 'Food Services'
                  jobCount: 888
                - sfwSectorTitle: 'Energy & Power'
                  jobCount: 123
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  body:
                    type: string
                    description: JSON string containing the details
              examples:
                emptyCodeOrQuarter:
                  summary: ssocCode / quarter empty
                  value:
                    statusCode: 400
                    body: "{\"message\": \"ssocCode and quarter cannot be empty\"}"
                invalidSsocCodeFormat:
                  summary: ssocCode format invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid ssocCode format. Expect format: Numeric string (e.g. 12345)\"}"
                invalidSsocCode:
                  summary: ssocCode invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid ssocCode\"}"
                invalidQuarterFormat:
                  summary: quarter format invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid quarter format. Expect format: YYYYQn (e.g. 2025Q1)\"}"
        '404':
          description: Demand not found
        '401':
          description: Unauthorized (if not public)
        '500':
          description: Server Error
          
  /companies/jobCount/{ssocCode}/{sfwSectorTitle}/{quarter}:
    get:
      tags:
        - Data APIs
      parameters:
      - name: ssocCode
        example: '25122'
        in: path
        description: ssoc of the job to analyse, cannot be null
        required: true
        schema:
          type: string
      - name: sfwSectorTitle
        example: 'Financial Services'
        in: path
        description: Name of the sector in URL encoded TitleCase, must support 'All' option that excludes the 'null' sector. Cannot be null
        required: true
        schema: 
          type: string
      - name: quarter
        example: 2025Q1
        in: path
        description: Time period for the data
        required: true
        schema:
          type: string
      - name: resultCount
        example: 20
        in: query
        description: Max number of results, if not provided to return 50
        schema:
          type: number
      - name: jobCountThreshold
        example: 20
        in: query
        description: Minimum jobCount that the results should have e.g. if set to 20, companies with 19 or less jobCount will be omitted from the response. Defaults to 1
        schema:
          type: number  
      summary: Get job count per company with sector annotations ordered by job count
      description: On client side we will first be querying across all sectors, if a sector filter is selected we will then run a sector specific query to display only the selected sector's entries. To exclude companies with 0 job count. Sort by job count descending (highest first). Data refresh cycle at 28 days after end of each quarter.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/CompanyResponse'
              example:
                ssocVersion: '2020'
                ssocTitle: 'Web And Mobile Applications Developer'
                data:
                  - companyName: 'DBS Bank LTD.'
                    jobCount: 123
                    sfwSectorTitle: 'Financial Services'
                    isRecruiter: 0
                  - companyName: 'Some food company'
                    jobCount: 45
                    sfwSectorTitle: 'Food Services'
                    isRecruiter: 0
                  - companyName: 'Singapore Power'
                    jobCount: 23
                    sfwSectorTitle: 'Energy & Power'
                    isRecruiter: 0
                  - companyName: 'Singapore Telecom Services'
                    jobCount: 20
                    sfwSectorTitle: 'Infocomm Technology'
                    isRecruiter: 0
                  - companyName: 'Maximum Talent'
                    jobCount: 13
                    sfwSectorTitle: 'Recruitment Agencies'
                    isRecruiter: 1
                  - companyName: 'OCBC Bank'
                    jobCount: 5
                    sfwSectorTitle: 'Financial Services'
                    isRecruiter: 0
                  - companyName: 'Maybank'
                    jobCount: 1
                    sfwSectorTitle: 'Financial Services'
                    isRecruiter: 0
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  body:
                    type: string
                    description: JSON string containing the details
              examples:
                emptyCodeOrQuarter:
                  summary: ssocCode / sfwSectorTitle / quarter empty
                  value:
                    statusCode: 400
                    body: "{\"message\": \"ssocCode, sfwSectorTitle, and quarter cannot be empty\"}"
                invalidSsocCodeFormat:
                  summary: ssocCode format invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid ssocCode format. Expect format: Numeric string (e.g. 12345)\"}"
                invalidSsocCode:
                  summary: ssocCode invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid ssocCode\"}"
                invalidQuarterFormat:
                  summary: quarter format invalid
                  value:
                    statusCode: 400
                    body: "{\"message\": \"Invalid quarter format. Expect format: YYYYQn (e.g. 2025Q1)\"}"
        '404':
          description: Demand not found
        '401':
          description: Unauthorized (if not public)
        '500':
          description: Server Error
          
  /skills/{ssocCode}:
    get:
      tags:
        - Graph APIs
      parameters:
      - name: ssocCode
        example: '25122'
        in: path
        description: Name of the job to analyse
        required: true
        schema:
          type: string
      summary: Get the top 10 skills required for this job role
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 'Microsoft Access'
              example:
              - Javascript
              - Python
              - Android
              - Kotlin
              - C
              - C++
              - C#
              - Unity
              - Assembly
              - Go
        '404':
          description: Skills not found

  /courses:
    post:
      tags:
        - Graph APIs
      summary: Get list of courses based on a provided list of skills
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input_dict:
                  type: object
                  properties:
                    skill_list:
                      type: array
                      items:
                        type: string
                      example:
                        - "compensation management"
                        - "benefits management"
                        - "cost management"
                        - "python"
                    fees_importance:
                      type: integer
                      minimum: 0
                      maximum: 100
                      example: 50
                    duration_importance:
                      type: integer
                      minimum: 0
                      maximum: 100
                      example: 50
                  required:
                    - skill_list
                    - fees_importance
                    - duration_importance
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '404':
          description: Courses not found
      
components:
  schemas:
    Job:
      required:
        - ssocTitle
        - ssocCode
      type: object
      properties:
        ssocTitle:
          type: string
          example: 'Web and mobile applications developer'
        ssocCode:
          type: string
          example: '25122'
    Pathway:
      required:
        - destinationRole
        - ssocSimilarityScore
        - ssocSimilarityCategory
        - ssocSkillGap
        - ssocMedianWage
        - jobCount
      type: object
      properties:
        destinationRole:
          type: object
          properties:
            ssocTitle:
              type: string
              example: 'Web and mobile applications developer'
            ssocCode:
              type: string
              example: '25122'
        ssocSimilarityScore:
          type: number
          example: 0.75
        ssocSimilarityCategory:
          type: string
          example: 'Medium'
        ssocSkillGap:
          type: array
          items:
            type: string
            example: 'Tools Development'
        ssocMedianWage:
          type: number
          example: 6100
        jobCount:
          type: number
          example: 100
    SectorResponse:
      required:
        - ssocTitle
        - ssocVersion
        - data
      type: object
      properties:
        ssocTitle:
          type: string
          example: 'Web And Mobile Applications Developer'
        ssocVersion:
          type: string
          example: '2020'
        data:
          type: array
          items:
          $ref: "#/components/schemas/Sector"
    Sector:
      required:
        - sfwSectorTitle
        - jobCount
      type: object
      properties:
        sfwSectorTitle:
          type: string
          example: 'Financial Services'
        jobCount:
          type: number
          example: 345
    CompanyResponse:
      required:
        - ssocTitle
        - ssocVersion
        - data
      type: object
      properties:
        ssocTitle:
          type: string
          example: 'Web And Mobile Applications Developer'
        ssocVersion:
          type: string
          example: '2020'
        data:
          type: array
          items:
          $ref: "#/components/schemas/Company"
    Company:
      required:
        - companyName
        - jobCount
        - sfwSectorTitle
        - isRecruiter
      type: object
      properties:
        companyName:
          type: string
          description: Name of the company, cannot be null
          example: 'DBS Bank'
        jobCount:
          type: number
          example: 345
        sfwSectorTitle:
          type: string
          description: Name of the sector, cannot be null
          example: 'Financial Services'
        isRecruiter:
          type: number
          description: represents a boolean, can only be either 1 or 0
          example: 0
    Course:
      required:
        - courseTitle
        - courseReferenceNumber
        - courseFee
        - courseDurationHour
        - courseSkillTaught
        - msfLink
      type: object
      properties:
        courseTitle:
          type: string
          example: 'Certified Ethical Hacker (CEH)'
        courseReferenceNumber:
          type: string
          example: 'TGS-2018504800'
        courseFee:
          type: string
          example: '2500'
        courseDurationHour:
          type: string
          example: '40'
        courseSkillTaught:
          type: array
          items:
            type: string
            example: 'Microsoft Access'
        msfLink:
          type: string
          example: 'https://www.myskillsfuture.gov.sg/content/portal/en/training-exchange/course-directory/course-detail.html?courseReferenceNumber=TGS-2023035654'